version: "3.9"

services:

  db:
    image: postgres:16
    container_name: astrom_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: astrom
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    container_name: astrom_api
    command: >
      sh -c "alembic upgrade head && uvicorn src.testastrom.main:app --host 0.0.0.0 --port 8000"

    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/astrom
    volumes:
      - .:/app

volumes:
  pgdata: